version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - secnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    networks:
      - secnet

  scanner:
    build: .
    volumes:
      - ./scan_results:/app/scan_results
    environment:
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - secnet

  web-ui:
    build: .
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
    ports:
      - "5000:5000"
    volumes:
      - ./scan_results:/app/scan_results
    depends_on:
      - elasticsearch
    networks:
      - secnet

volumes:
  esdata:

networks:
  secnet:
    driver: bridge